[package]
name = "optional-index"
version = "0.1.0"
authors = ["kgv <kgv@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
description = "Optional indexing operations."
categories = ["no-std", "rust-patterns"]
edition = "2018"

[dev-dependencies]
maplit = "1.0.2"